2018-03-09 00:23:11,229 ERROR: Exception on /register [GET] [in /home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seng/microblog/app/routes.py", line 71, in register
    return render_template('register.html', title='Register', form=form)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/seng/microblog/app/templates/register.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/seng/microblog/app/templates/base.html", line 23, in top-level template code
    <a href="{{ url_for('payroll')}}">Payroll</a>
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'payroll'. Did you mean 'edit_profile' instead?
2018-03-09 00:24:58,100 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:25:02,349 ERROR: Exception on /login [GET] [in /home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seng/microblog/app/routes.py", line 52, in login
    return render_template('login.html',title='Sign In', form = form)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/seng/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/seng/microblog/app/templates/base.html", line 23, in top-level template code
    <a href="{{ url_for('payroll')}}">Payroll</a>
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'payroll'. Did you mean 'edit_profile' instead?
2018-03-09 00:27:15,866 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:28:39,942 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:30:22,646 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:31:26,957 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:34:57,602 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:37:25,341 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:37:35,001 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:39:11,295 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:40:30,134 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:46:43,517 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:47:31,830 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:52:36,831 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:53:25,827 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:53:45,272 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:56:34,852 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:56:54,610 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:58:54,894 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:59:46,625 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 00:59:58,538 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
2018-03-09 01:02:09,424 INFO: Microblog startup [in /home/seng/microblog/app/__init__.py:44]
