2018-03-21 02:23:59,317 ERROR: Exception on /manager [GET] [in /home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seng/dev/Python-Online-Ordering-System/app/routes.py", line 21, in decorated_view
    return fn(*args, **kwargs)
  File "/home/seng/dev/Python-Online-Ordering-System/app/routes.py", line 65, in manager
    return render_template('managers/manager.html')
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/seng/dev/Python-Online-Ordering-System/app/templates/base.html", line 21, in template
    {% if not {current_user.is_manager} %}
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/seng/dev/Python-Online-Ordering-System/app/templates/managers/manager.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/seng/dev/Python-Online-Ordering-System/app/templates/base.html", line 21, in template
    {% if not {current_user.is_manager} %}
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 211, in parse_if
    node.test = self.parse_tuple(with_condexpr=False)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 620, in parse_tuple
    args.append(parse())
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 612, in <lambda>
    parse = lambda: self.parse_expression(with_condexpr=False)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 433, in parse_expression
    return self.parse_or()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 469, in parse_not
    return nodes.Not(self.parse_not(), lineno=lineno)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 581, in parse_primary
    node = self.parse_dict()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 662, in parse_dict
    self.stream.expect('colon')
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
2018-03-21 02:37:44,912 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 02:38:17,409 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 02:39:18,696 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 02:42:17,287 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 02:42:42,173 ERROR: Exception on /manager [GET] [in /home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seng/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seng/dev/Python-Online-Ordering-System/app/routes.py", line 20, in decorated_view
    return current_app.login_manager.unauthorized()
NameError: name 'current_app' is not defined
2018-03-21 02:44:03,255 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 02:46:12,431 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 02:52:30,981 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 02:54:04,059 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 02:55:19,480 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 02:56:38,132 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 02:58:42,646 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 03:09:38,222 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 03:14:41,185 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 03:15:14,267 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 03:15:57,602 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
2018-03-21 03:16:12,474 INFO: Microblog startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:48]
