2018-03-21 15:09:59,590 INFO: Cake-Online-System startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:45]
2018-03-21 15:15:59,328 INFO: Cake-Online-System startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:45]
2018-03-21 15:18:27,251 INFO: Cake-Online-System startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:45]
2018-03-21 15:18:52,287 INFO: Cake-Online-System startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:45]
2018-03-21 15:19:30,535 INFO: Cake-Online-System startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:45]
2018-03-21 15:20:00,750 INFO: Cake-Online-System startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:45]
2018-03-21 15:24:34,400 INFO: Cake-Online-System startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:45]
2018-03-21 15:31:51,209 INFO: Cake-Online-System startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:45]
2018-03-21 15:55:22,742 INFO: Cake-Online-System startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:45]
2018-03-21 15:55:33,166 ERROR: Exception on /cookcustorder [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seng/dev/Python-Online-Ordering-System/app/routes.py", line 20, in decorated_view
    return fn(*args, **kwargs)
  File "/home/seng/dev/Python-Online-Ordering-System/app/routes.py", line 65, in cookcustorder
    return render_template('cooks/cookcustorder.html',title = 'Cook')
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seng/dev/Python-Online-Ordering-System/app/templates/cooks/cookcustorder.html", line 1, in template
    {% extends "base.html"}
TemplateSyntaxError: unexpected '}'
2018-03-21 15:55:54,828 INFO: Cake-Online-System startup [in /home/seng/dev/Python-Online-Ordering-System/app/__init__.py:45]
